// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaL1LY8BQIotbk2dFBdvHcyBlzjGS62Dg',
    appId: '1:485931116060:web:61c3e41df5c2b04a1a61d9',
    messagingSenderId: '485931116060',
    projectId: 'student-help-portal-184a3',
    authDomain: 'student-help-portal-184a3.firebaseapp.com',
    storageBucket: 'student-help-portal-184a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7WXMup1EhpFrHVWbdKf4CiFDIX2pJuI',
    appId: '1:485931116060:android:54b7d1a27e77655b1a61d9',
    messagingSenderId: '485931116060',
    projectId: 'student-help-portal-184a3',
    storageBucket: 'student-help-portal-184a3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaL1LY8BQIotbk2dFBdvHcyBlzjGS62Dg',
    appId: '1:485931116060:web:2dcf72269b7643231a61d9',
    messagingSenderId: '485931116060',
    projectId: 'student-help-portal-184a3',
    authDomain: 'student-help-portal-184a3.firebaseapp.com',
    storageBucket: 'student-help-portal-184a3.firebasestorage.app',
  );

}